//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Worship
{
    using System;
    using System.Collections.Generic;
    
    public partial class equipe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public equipe()
        {
            this.equipe_integrantes = new HashSet<equipe_integrante>();
        }
    
        public sbyte cd_equipe { get; set; }
        public string tx_nome_equipe { get; set; }
        public sbyte nr_ano { get; set; }
        public Nullable<bool> nr_domingo { get; set; }
        public string cd_integrante_lider { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<equipe_integrante> equipe_integrantes { get; set; }
    }
}
