//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Worship
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class equipe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public equipe()
        {
            this.equipe_integrantes = new HashSet<equipe_integrante>();
            this.eventos = new HashSet<evento>();
        }

        [Key]
        public sbyte cd_equipe { get; set; }
        [Required(ErrorMessage = "Digite o nome da equipe")]
        [StringLength(10, ErrorMessage = "Nome da equipe deve ter no máximo 10 caracteres")]
        [Display(Name = "Nome da equipe")]
        public string tx_nome_equipe { get; set; }
        [Required(ErrorMessage = "Escolha o ano de referência")]
        [Range(2016, 2025, ErrorMessage = "Ano inválido")]
        [Display(Name = "Ano")]
        public short nr_ano { get; set; }
        [Range(1, 5, ErrorMessage = "Domingo deve ser um número entre 1 e 5")]
        [Display(Name = "Domingo do mês")]
        public Nullable<sbyte> nr_domingo { get; set; }
        [Display(Name = "Líder da equipe")]
        public Nullable<sbyte> cd_integrante_lider { get; set; }

        public int nrIntegrantes { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<equipe_integrante> equipe_integrantes { get; set; }
        public virtual integrante lider { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<evento> eventos { get; set; }
    }
}
