//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Worship
{
    using System;
    using System.Collections.Generic;
    
    public partial class evento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public evento()
        {
            this.evento_musicas = new HashSet<evento_musica>();
            this.evento_integrantes = new HashSet<evento_integrante>();
        }
    
        public System.DateTime dt_evento { get; set; }
        public sbyte cd_tipo_evento { get; set; }
        public Nullable<sbyte> cd_equipe { get; set; }
        public string tx_comentarios { get; set; }
    
        public virtual tipo_evento tipo_evento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<evento_musica> evento_musicas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<evento_integrante> evento_integrantes { get; set; }
    }
}
