//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Worship
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class hino_genero
    {
        [Key]
        [Column(Order = 0)]
        [Display(Name = "Música")]
        public short cd_hino { get; set; }
        [Key]
        [Column(Order = 1)]
        [Display(Name = "Gênero")]
        public sbyte cd_genero { get; set; }
        [Key]
        [Column(Order = 2)]
        [Display(Name = "Tipo")]
        public string id_genero { get; set; }
    
        public virtual genero_musica genero_musica { get; set; }
        public virtual genero_letra genero_letra { get; set; }
        public virtual hino hino { get; set; }
    }
}
