//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Worship
{
    using System;
    using System.Collections.Generic;
    
    public partial class hino
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hino()
        {
            this.hino_generos = new HashSet<hino_genero>();
            this.evento_musicas = new HashSet<evento_musica>();
        }
    
        public int cd_hino { get; set; }
        public string tx_titulo_hino { get; set; }
        public string tx_inicio { get; set; }
        public string tx_nome_compositor_letra { get; set; }
        public string tx_nome_compositor_musica { get; set; }
        public Nullable<long> nr_ano { get; set; }
        public string tx_tonalidade { get; set; }
    
        public virtual tonalidade tonalidade { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hino_genero> hino_generos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<evento_musica> evento_musicas { get; set; }
    }
}
