//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Worship
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class hino
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hino()
        {
            this.hino_generos = new HashSet<hino_genero>();
            this.evento_musicas = new HashSet<evento_musica>();
        }

        [Key]
        public short cd_hino { get; set; }
        [Required(ErrorMessage = "Digite o título da música")]
        [StringLength(50, ErrorMessage = "O título da música deve ter no máximo 50 caracteres")]
        [Display(Name = "Título")]
        public string tx_titulo_hino { get; set; }
        [StringLength(50, ErrorMessage = "O início da música deve ter no máximo 50 caracteres")]
        [Display(Name = "Início")]
        public string tx_inicio { get; set; }
        [StringLength(50, ErrorMessage = "O nome do compositor da letra deve ter no máximo 50 caracteres")]
        [Display(Name = "Letra")]
        public string tx_nome_compositor_letra { get; set; }
        [StringLength(50, ErrorMessage = "O nome do compositor da m~usica deve ter no máximo 50 caracteres")]
        [Display(Name = "Música")]
        public string tx_nome_compositor_musica { get; set; }
        [Range(1000, 9999, ErrorMessage = "Ano inválido")]
        [Display(Name = "Ano")]
        public Nullable<long> nr_ano { get; set; }
        [Required(ErrorMessage = "Informe a tonalidade")]
        [StringLength(3, ErrorMessage = "Tonalidade deve ter no máximo 3 caracteres")]
        [Display(Name = "Tonalidade")]
        public string tx_tonalidade { get; set; }

        [Display(Name = "Utilizações")]
        public int nrUtilizacoes { get; set; }

        public virtual tonalidade tonalidade { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hino_genero> hino_generos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<evento_musica> evento_musicas { get; set; }
    }
}
