//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Worship
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class integrante
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public integrante()
        {
            this.equipe_integrantes = new HashSet<equipe_integrante>();
            this.evento_integrantes = new HashSet<evento_integrante>();
            this.equipes = new HashSet<equipe>();
        }

        [Key]
        public sbyte cd_integrante { get; set; }
        [Required(ErrorMessage = "Digite o nome completo do integrante")]
        [StringLength(45, ErrorMessage = "Nome do integrante deve ter no máximo 45 caracteres")]
        [Display(Name = "Nome do integrante")]
        public string tx_nome_integrante { get; set; }
        [StringLength(45, ErrorMessage = "Email do integrante deve ter no máximo 45 caracteres")]
        [EmailAddress(ErrorMessage = "Endereço de email inválido")]
        [Display(Name = "Email do integrante")]
        public string tx_email_integrante { get; set; }
        [StringLength(15, ErrorMessage = "Nome curto do integrante deve ter no máximo 15 caracteres")]
        [Display(Name = "Nome curto do integrante")]
        public string tx_nome_curto_integrante { get; set; }
        [Display(Name = "Foto do integrante")]
        public byte[] foto_integrante { get; set; }

        public bool integrante_em_uso { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<equipe_integrante> equipe_integrantes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<evento_integrante> evento_integrantes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<equipe> equipes { get; set; }
    }
}
