//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Worship
{
    using System;
    using System.Collections.Generic;
    
    public partial class integrante
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public integrante()
        {
            this.equipe_integrantes = new HashSet<equipe_integrante>();
            this.evento_integrantes = new HashSet<evento_integrante>();
        }
    
        public sbyte cd_integrante { get; set; }
        public string tx_nome_integrante { get; set; }
        public string tx_email_integrante { get; set; }
        public string tx_nome_curto_integrante { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<equipe_integrante> equipe_integrantes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<evento_integrante> evento_integrantes { get; set; }
    }
}
