//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Worship
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tipo_evento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tipo_evento()
        {
            this.eventos = new HashSet<evento>();
        }

        [Key]
        public sbyte cd_tipo_evento { get; set; }
        [Key]
        [Required(ErrorMessage = "Digite o tipo de evento")]
        [StringLength(45, ErrorMessage = "Tipo de evento deve ter no máximo 45 caracteres")]
        [Display(Name = "Tipo de evento")]
        public string tx_tipo_evento { get; set; }

        [Display(Name = "Qt. Eventos")]
        public int nrEventosUsando { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<evento> eventos { get; set; }
    }
}
