//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Worship
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public string tx_login { get; set; }
        public string tx_nome_usuario { get; set; }
        public string tx_nome_guerra { get; set; }
        public string tx_senha { get; set; }
        public string tx_email { get; set; }
        public Nullable<System.DateTime> dt_ultimo_login { get; set; }
    }
}
