//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Worship
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class worshipEntities : DbContext
    {
        public worshipEntities()
            : base("name=worshipEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<genero_letra> genero_letra { get; set; }
        public virtual DbSet<genero_musica> genero_musica { get; set; }
        public virtual DbSet<tonalidade> tonalidade { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
        public virtual DbSet<hino_genero> hino_genero { get; set; }
        public virtual DbSet<equipe> equipe { get; set; }
        public virtual DbSet<equipe_integrante> equipe_integrante { get; set; }
        public virtual DbSet<evento> evento { get; set; }
        public virtual DbSet<evento_integrante> evento_integrante { get; set; }
        public virtual DbSet<evento_musica> evento_musica { get; set; }
        public virtual DbSet<integrante> integrante { get; set; }
        public virtual DbSet<tipo_evento> tipo_evento { get; set; }
        public virtual DbSet<hino> hino { get; set; }
    }
}
